/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.unlar.FinalPyLIII.ui;

import ar.edu.unlar.FinalPyLIII.objetos.Turno;
import ar.edu.unlar.FinalPyLIII.grillas.TurnoGrilla;
import ar.edu.unlar.FinalPyLIII.controladores.TurnoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author DjNiico
 */
public class PREABMTurno extends javax.swing.JInternalFrame {
    Turno tu,t;
    TurnoDTO turnoDTO;
    private TurnoGrilla turnoGrillas;
    private   ArrayList <Turno> listadoTurnos;
    /**
     * Creates new form PREABMTurnos
     */
    public PREABMTurno() {
        initComponents();
        actualizaGrilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turnoGrilla1 = new ar.edu.unlar.FinalPyLIII.grillas.TurnoGrilla();
        turno1 = new ar.edu.unlar.FinalPyLIII.objetos.Turno();
        turnoDTO1 = new ar.edu.unlar.FinalPyLIII.controladores.TurnoDTO();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBtnNuevo1 = new javax.swing.JButton();
        jBtnEliminar1 = new javax.swing.JButton();
        jBtnEditar1 = new javax.swing.JButton();
        JBtnCerrar1 = new javax.swing.JButton();

        setClosable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLE DE TURNO"));

        jLabel8.setText("Codigo:");

        jLabel9.setText("Descripcion:");

        jTxtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDescripcionActionPerformed(evt);
            }
        });

        jTDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTDatos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnNuevo1.setText("Nuevo");
        jBtnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevo1ActionPerformed(evt);
            }
        });

        jBtnEliminar1.setText("Eliminar");
        jBtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminar1ActionPerformed(evt);
            }
        });

        jBtnEditar1.setText("Editar");
        jBtnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNuevo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEditar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEliminar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditar1)
                    .addComponent(jBtnNuevo1)
                    .addComponent(jBtnEliminar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JBtnCerrar1.setText("Cerrar");
        JBtnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCerrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(500, 500, 500)
                                .addComponent(JBtnCerrar1))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(JBtnCerrar1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDatosMouseClicked

        int filaSelec= jTDatos.getSelectedRow();

        String  b,c;

        if (filaSelec>=0)
        {

            b=   jTDatos.getValueAt(filaSelec, 1).toString();
            c= jTDatos.getValueAt(filaSelec, 2).toString();

            jTxtCodigo.setText(b);
            jTxtDescripcion.setText(c);

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
    }//GEN-LAST:event_jTDatosMouseClicked

    private void jTxtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDescripcionActionPerformed

    private void jBtnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevo1ActionPerformed

        if(jTxtDescripcion.getText().length()>2  &&  Integer.parseInt(jTxtCodigo.getText())>0)
        {
            t = new Turno();
            t.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
            t.setDescripcion(jTxtDescripcion.getText());
            turnoDTO= new TurnoDTO( );
            if(!turnoDTO.extraerTodo().contains(t)){
                turnoDTO.crear(t);
                JOptionPane.showMessageDialog(this, "TURNO GENERADO");
            }
            else{
                JOptionPane.showMessageDialog(this, "YA EXISTE");
            }

            actualizaGrilla();
        }
        else{
            JOptionPane.showMessageDialog(null, "La Descripcion debe contener mas de 2 caracteres y el codigo debe ser distinto de cero");

        }

        limpiar();

    }//GEN-LAST:event_jBtnNuevo1ActionPerformed

    private void jBtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminar1ActionPerformed
        int filaSelec= jTDatos.getSelectedRow();
        int a;
        Turno t = new Turno();
        TurnoDTO turnodto = new  TurnoDTO();

        if (filaSelec>=0)
        {
            a=(Integer) jTDatos.getValueAt(filaSelec,0);
            turnoGrillas.borrarFilas(jTDatos.getSelectedRow());
            t.setId(a);
            turnodto.eliminar(t);
            limpiar();
            actualizaGrilla();

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
    }//GEN-LAST:event_jBtnEliminar1ActionPerformed

    private void jBtnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditar1ActionPerformed
        int filaSelec= jTDatos.getSelectedRow();
        int a;
        t = new Turno();
        turnoDTO= new  TurnoDTO();

        if (filaSelec>=0)
        {
            a=(Integer)jTDatos.getValueAt(filaSelec,0);

            if(jTxtDescripcion.getText().length()>2  &&  Integer.parseInt(jTxtCodigo.getText())>0)
            {
                t.setId(a);
                t.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
                t.setDescripcion(jTxtDescripcion.getText());
                if(!turnoDTO.extraerTodo().contains(t)){
                    turnoDTO.modificar(t);
                    JOptionPane.showMessageDialog(this, "TURNO MODIFICADO");
                }
                else{
                    JOptionPane.showMessageDialog(this, "YA EXISTE");
                }

                actualizaGrilla();
            }
            else{
                JOptionPane.showMessageDialog(null, "La Descripcion debe contener mas de 2 caracteres y el codigo ser distinto de cero");

            }

            limpiar();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
    }//GEN-LAST:event_jBtnEditar1ActionPerformed

    private void JBtnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCerrar1ActionPerformed
        dispose();
    }//GEN-LAST:event_JBtnCerrar1ActionPerformed

    public void limpiar(){
    jTxtCodigo.setText("");
    jTxtDescripcion.setText("");
    
    }
 
    private void actualizaGrilla(){
        turnoDTO= new TurnoDTO();
        listadoTurnos= turnoDTO.extraerTodo();
        turnoGrillas = new TurnoGrilla(listadoTurnos);
          
         jTDatos.setModel(turnoGrillas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnCerrar1;
    private javax.swing.JButton jBtnEditar1;
    private javax.swing.JButton jBtnEliminar1;
    private javax.swing.JButton jBtnNuevo1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescripcion;
    private ar.edu.unlar.FinalPyLIII.objetos.Turno turno1;
    private ar.edu.unlar.FinalPyLIII.controladores.TurnoDTO turnoDTO1;
    private ar.edu.unlar.FinalPyLIII.grillas.TurnoGrilla turnoGrilla1;
    // End of variables declaration//GEN-END:variables
}
