/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.unlar.FinalPyLIII.ui;

import ar.edu.unlar.FinalPyLIII.controladores.AlumnoDTO;
import ar.edu.unlar.FinalPyLIII.controladores.GradoDTO;
import ar.edu.unlar.FinalPyLIII.grillas.AlumnoGrilla;
import ar.edu.unlar.FinalPyLIII.objetos.Alumno;
import ar.edu.unlar.FinalPyLIII.objetos.Grado;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DjNiico
 */
public class PREABMAlumnos extends javax.swing.JInternalFrame {

    private AlumnoDTO alumnodto;
private Alumno a;
DefaultComboBoxModel<Grado>boxModel;
ArrayList<Grado> gradoAux= new ArrayList<>();
GradoDTO gradoDto = new GradoDTO(); 
  private   AlumnoGrilla alumnoGrillas;
  
  private  ArrayList <Alumno> listadoAlumnos;
    public PREABMAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alumnoDTO1 = new ar.edu.unlar.FinalPyLIII.controladores.AlumnoDTO();
        alumnoGrilla1 = new ar.edu.unlar.FinalPyLIII.grillas.AlumnoGrilla();
        alumno1 = new ar.edu.unlar.FinalPyLIII.objetos.Alumno();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDato = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jTxtFechaNacimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtMatricula = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jCmbGrado = new javax.swing.JComboBox();
        jCmbSexo = new javax.swing.JComboBox<>();
        jTxtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jBtnBuscar = new javax.swing.JButton();
        JBtnCerrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jTDato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDatoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTDato);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLE DE ALUMNO"));

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido:");

        jTxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApellidoActionPerformed(evt);
            }
        });

        jLabel10.setText("Documento:");

        jLabel11.setText("Fecha Nacimiento: ");

        jLabel12.setText("Sexo:");

        jLabel13.setText("Grado:");

        jTxtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMatriculaActionPerformed(evt);
            }
        });

        jLabel14.setText("Matricula:");

        jCmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCmbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jCmbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtMatricula))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jTxtDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jTxtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCmbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        jTxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEliminar)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Buscar:");

        jBtnBuscar.setText("Buscar");

        JBtnCerrar.setText("Cerrar");
        JBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCerrarActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBuscar)
                            .addComponent(JBtnCerrar)))
                    .addComponent(jTextField1))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDatoMouseClicked
        int filaSelec= jTDato.getSelectedRow();

        String c;

        if (filaSelec>=0)
        {
            //          b= jTDato.getValueAt(filaSelec, 2).toString();
            c= jTDato.getValueAt(filaSelec, 3).toString();

            //          jTxtApellido.setText(b);
            jTxtMatricula.setText(c);

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
    }//GEN-LAST:event_jTDatoMouseClicked

    private void jTxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApellidoActionPerformed

    private void jTxtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMatriculaActionPerformed

    private void jTxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBuscarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed

        if(jTxtNombre.getText().length()>2  && jTxtApellido.getText().length()>2   &&  jTxtDocumento.getText().length()>2   &&Integer.parseInt(jTxtMatricula.getText())>0)
        {
            a = new Alumno();

            a.setNombre(jTxtNombre.getText());
            a.setApellido(jTxtApellido.getText());
            a.setDocumento(jTxtDocumento.getText());
            a.setFechaNacimiento(jTxtFechaNacimiento.getText());
            a.setSexo((String) jCmbSexo.getSelectedItem());
            a.setGrado((Grado)jCmbGrado.getSelectedItem());
            a.setMatricula(Integer.parseInt(jTxtMatricula.getText()));

            alumnodto = new AlumnoDTO();
            if(!alumnodto.extraerTodo().contains(a)){
                alumnodto.crear(a);
                JOptionPane.showMessageDialog(this, "ALUMNO CARGADO");
            }
            else{
                JOptionPane.showMessageDialog(this, "YA EXISTE UN ALUMNO CON ESA MATRICULA");
            }

            actualizaGrilla();
        } else{
            JOptionPane.showMessageDialog(null, "Los campos de palabras deben contener 3 letras como minimo y los numeros no pueden ser 0");
        }

        limpiar();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        int filaSelec= jTDato.getSelectedRow();
        //        int g;

        if (filaSelec>=0)
        {

            JOptionPane.showMessageDialog(this, "EN PROCESO DE CONSTRUCCION");
            //            Alumno alumno = new Alumno();
            //          AlumnoDTO alumnoDTO= new  AlumnoDTO();
            //                g=(Integer)jTDato.getValueAt(filaSelec,0);
            //
            //           alumno.setIdAlumno(g);
            //           alumno.setNombre(jTxtNombre.getText());
            //           alumno.setApellido(jTxtApellido.getText());
            //           alumno.setDocumento(jTxtDocumento.getText());
            //           alumno.setFechaNacimiento(jTxtFechaNacimiento.getText());
            //           alumno.setSexo((String) jCmbSexo.getSelectedItem());
            //           alumno.setGrado((Grado)jCmbGrado.getSelectedItem());
            //           alumno.setMatricula(Integer.parseInt(jTxtMatricula.getText()));
            //            if(!alumnoDTO.extraerTodo().contains(alumno)){
                //         alumnoDTO.modificar(alumno);
                //             JOptionPane.showMessageDialog(this, "ALUMNO EDITADO");
                //             }else{
                //              JOptionPane.showMessageDialog(this, "ALUMNO YA EXISTE");
                //                }
            //
            //
            //          actualizaGrilla();

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
        limpiar();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        int filaSelec= jTDato.getSelectedRow();
        int d;
        Alumno al = new Alumno();
        AlumnoDTO alumnoDTO = new  AlumnoDTO();

        if (filaSelec>=0)
        {
            d=(Integer) jTDato.getValueAt(filaSelec,0);
            alumnoGrillas.borrarFilas(jTDato.getSelectedRow());
            al.setIdAlumno(d);
            alumnoDTO.eliminar(al);
            limpiar();
            actualizaGrilla();

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void JBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_JBtnCerrarActionPerformed
     public void limpiar(){
    jTxtDocumento.setText("");
    jTxtApellido.setText("");
    jTxtFechaNacimiento.setText("");
    jTxtMatricula.setText("");
    jTxtNombre.setText("");
 
           
    
    }
 private void cargarComboGrado() {
    ArrayList<Grado>grado = (ArrayList<Grado>) gradoDto.extraerTodo();
        
    Grado[] gradoAux1= new Grado[grado.size()];
    for (int i = 0; i < grado.size(); i++) {
        gradoAux1[i]=grado.get(i);
    }
    boxModel=new DefaultComboBoxModel<>(gradoAux1);
     jCmbGrado.setModel(boxModel);
     jCmbGrado.setSelectedItem(null);
    }
 
   private void actualizaGrilla(){
        alumnodto= new AlumnoDTO();
        listadoAlumnos= alumnodto.extraerTodo();
        alumnoGrillas = new AlumnoGrilla(listadoAlumnos);
          
         jTDato.setModel(alumnoGrillas);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnCerrar;
    private ar.edu.unlar.FinalPyLIII.objetos.Alumno alumno1;
    private ar.edu.unlar.FinalPyLIII.controladores.AlumnoDTO alumnoDTO1;
    private ar.edu.unlar.FinalPyLIII.grillas.AlumnoGrilla alumnoGrilla1;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox jCmbGrado;
    private javax.swing.JComboBox<String> jCmbSexo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTDato;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtBuscar;
    private javax.swing.JTextField jTxtDocumento;
    private javax.swing.JTextField jTxtFechaNacimiento;
    private javax.swing.JTextField jTxtMatricula;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
