/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.unlar.FinalPyLIII.ui;

import ar.edu.unlar.FinalPyLIII.controladores.CargoDTO;
import ar.edu.unlar.FinalPyLIII.grillas.CargoGrilla;
import ar.edu.unlar.FinalPyLIII.objetos.Cargo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DjNiico
 */
public class PREABMCargo extends javax.swing.JInternalFrame {
 Cargo c;
 CargoDTO cargoDTO;
 private CargoGrilla cargoGrillas;
 private   ArrayList <Cargo> listadoCargos;
    /**
     * Creates new form PREABMCargo
     */
    public PREABMCargo() {
        initComponents();
         actualizaGrilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargoGrilla1 = new ar.edu.unlar.ProyectoFinal.UI.grillas.CargoGrilla();
        cargoDTO1 = new ar.edu.unlar.FinalPyLIII.controladores.CargoDTO();
        cargo1 = new ar.edu.unlar.FinalPyLIII.objetos.Cargo();
        jTxtBuscar1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnNuevo1 = new javax.swing.JButton();
        jBtnEditar1 = new javax.swing.JButton();
        jBtnEliminar1 = new javax.swing.JButton();
        jBtnBuscar1 = new javax.swing.JButton();
        JBtnCerrar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jTxtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBuscar1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Buscar:");

        jTDatos.setModel(cargoGrilla1);
        jTDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTDatos);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLE DE CARGO"));

        jLabel8.setText("Codigo:");

        jLabel9.setText("Descripcion:");

        jTxtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnNuevo1.setText("Nuevo");
        jBtnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevo1ActionPerformed(evt);
            }
        });

        jBtnEditar1.setText("Editar");
        jBtnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditar1ActionPerformed(evt);
            }
        });

        jBtnEliminar1.setText("Eliminar");
        jBtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo1)
                    .addComponent(jBtnEditar1)
                    .addComponent(jBtnEliminar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnBuscar1.setText("Buscar");
        jBtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscar1ActionPerformed(evt);
            }
        });

        JBtnCerrar1.setText("Cerrar");
        JBtnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCerrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtnCerrar1)
                            .addComponent(jBtnBuscar1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBuscar1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnCerrar1)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBuscar1ActionPerformed

    private void jTxtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDescripcionActionPerformed

    private void jBtnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevo1ActionPerformed

    if(jTxtDescripcion.getText().length()>2  &&  Integer.parseInt(jTxtCodigo.getText())>0)
        {
        c = new Cargo();
        c.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
        c.setDescripcion(jTxtDescripcion.getText());
        cargoDTO= new CargoDTO( );
        if(!cargoDTO.extraerTodo().contains(c)){
        cargoDTO.crear(c);
        JOptionPane.showMessageDialog(this, "CARGO CREADO");
         }
       else{
       JOptionPane.showMessageDialog(this, "CARGO YA EXISTE");
       }
        
        
        actualizaGrilla();
      }
        else{
          JOptionPane.showMessageDialog(null, "La Descripcion debe contener mas de 2 caracteres y el codigo debe ser distinto de cero"); 
     
        }
          limpiar();
    }//GEN-LAST:event_jBtnNuevo1ActionPerformed

    private void JBtnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCerrar1ActionPerformed
        dispose();
    }//GEN-LAST:event_JBtnCerrar1ActionPerformed

    private void jBtnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditar1ActionPerformed
         int filaSelec= jTDatos.getSelectedRow();
        int a;
      
        
        if (filaSelec>=0)
        {
          a=(Integer)jTDatos.getValueAt(filaSelec,0);
         if(jTxtDescripcion.getText().length()>2  &&  Integer.parseInt(jTxtCodigo.getText())>0)
          {
            c = new Cargo();
           
            c.setId(a);
            c.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
            c.setDescripcion(jTxtDescripcion.getText());
            cargoDTO= new  CargoDTO();
       	
            if(!cargoDTO.extraerTodo().contains(c)){
            cargoDTO.modificar(c);
             JOptionPane.showMessageDialog(this, "CARGO EDITADO");
             }else{
              JOptionPane.showMessageDialog(this, "CARGO YA EXISTE");
                }
        
             actualizaGrilla();
              }else{
          JOptionPane.showMessageDialog(null, "La Descripcion debe contener mas de 2 caracteres y el codigo debe ser distinto de cero"); 
          }     
            
        }
        else{
             JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
        }
        limpiar();
    }//GEN-LAST:event_jBtnEditar1ActionPerformed

    private void jBtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminar1ActionPerformed
        int filaSelec= jTDatos.getSelectedRow();
        int a;
         c = new Cargo();
         cargoDTO = new  CargoDTO();
        
        if (filaSelec>=0)
        {
          a=(Integer) jTDatos.getValueAt(filaSelec,0);
          cargoGrillas.borrarFilas(jTDatos.getSelectedRow());
          c.setId(a);
          cargoDTO.eliminar(c);	
          limpiar();
          actualizaGrilla();
        
        }
        else{
    JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
    }
    }//GEN-LAST:event_jBtnEliminar1ActionPerformed

    private void jTDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDatosMouseClicked
        int filaSelec= jTDatos.getSelectedRow();
      
        String  b,c;
           
        
        if (filaSelec>=0)
        {
          b=   jTDatos.getValueAt(filaSelec, 1).toString();
          c= jTDatos.getValueAt(filaSelec, 2).toString();
                  
          
            jTxtCodigo.setText(b);
          jTxtDescripcion.setText(c);
                  
        }
        else{
    JOptionPane.showMessageDialog(rootPane, "REGISTRO NO SELECCIONADO");
    }
    }//GEN-LAST:event_jTDatosMouseClicked

    private void jBtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscar1ActionPerformed
 public void limpiar(){
    jTxtCodigo.setText("");
    jTxtDescripcion.setText("");
    
    }
 
  private void actualizaGrilla(){
        cargoDTO= new CargoDTO();
        listadoCargos= cargoDTO.extraerTodo();
        cargoGrillas = new CargoGrilla(listadoCargos);
          
         jTDatos.setModel(cargoGrillas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnCerrar1;
    private ar.edu.unlar.FinalPyLIII.objetos.Cargo cargo1;
    private ar.edu.unlar.FinalPyLIII.controladores.CargoDTO cargoDTO1;
    private ar.edu.unlar.ProyectoFinal.UI.grillas.CargoGrilla cargoGrilla1;
    private javax.swing.JButton jBtnBuscar1;
    private javax.swing.JButton jBtnEditar1;
    private javax.swing.JButton jBtnEliminar1;
    private javax.swing.JButton jBtnNuevo1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    private javax.swing.JTextField jTxtBuscar1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescripcion;
    // End of variables declaration//GEN-END:variables
}
